# Generated by Django 5.0.4 on 2024-08-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_blogcategory_contactqueries_ourteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='article_images/'),
            preserve_default=False,
        ),
    ]
