# Generated by Django 5.0.4 on 2024-08-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_staticcontenthome'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('call', models.CharField(max_length=255)),
            ],
        ),
    ]
