# Generated by Django 5.0.4 on 2024-08-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_staticcontentabout_base_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontentabout',
            name='facebook_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='instagram_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='linkedin_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='twitter_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentcontact',
            name='facebook_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentcontact',
            name='instagram_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentcontact',
            name='linkedin_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentcontact',
            name='twitter_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='facebook_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='instagram_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='linkedin_url',
            field=models.URLField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='twitter_url',
            field=models.URLField(default='', max_length=255),
        ),
    ]
