# Generated by Django 5.0.4 on 2024-08-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_staticcontentblogdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseMeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider1',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider1_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider1_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider2_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider2_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider3',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider3_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider3_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider4',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider4_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='slider4_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider1',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider1_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider1_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider2',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider2_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider2_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider3',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider3_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider3_p2',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider4',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider4_p1',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='slider4_p2',
        ),
    ]
