# Generated by Django 5.0.4 on 2024-08-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_images/'),
        ),
    ]
