# Generated by Django 5.0.4 on 2024-08-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogcategory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=255)),
                ('og_title', models.CharField(max_length=255)),
                ('og_url', models.CharField(max_length=255)),
                ('og_image', models.CharField(max_length=255)),
                ('og_image_type', models.CharField(max_length=255)),
                ('og_image_width', models.CharField(max_length=255)),
                ('og_image_height', models.CharField(max_length=255)),
                ('og_type', models.CharField(max_length=255)),
                ('og_locale', models.CharField(max_length=255)),
                ('og_image_url', models.CharField(max_length=255)),
                ('og_image_secure_url', models.CharField(max_length=255)),
                ('og_site_name', models.CharField(max_length=255)),
                ('og_see_also', models.CharField(max_length=255)),
                ('article_author', models.CharField(max_length=255)),
                ('format_detection', models.CharField(max_length=255)),
            ],
        ),
    ]
