# Generated by Django 5.0.4 on 2024-08-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_seometa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometa',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='seometa',
            name='keywords',
            field=models.TextField(),
        ),
    ]
