# Generated by Django 5.0.4 on 2024-08-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_staticcontentcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContentAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('row1', models.CharField(max_length=500)),
                ('row2', models.CharField(max_length=500)),
                ('row3', models.CharField(max_length=500)),
                ('slider1', models.CharField(max_length=255)),
                ('slider1_p1', models.TextField()),
                ('slider1_p2', models.TextField()),
                ('slider2', models.CharField(max_length=255)),
                ('slider2_p1', models.TextField()),
                ('slider2_p2', models.TextField()),
                ('slider3', models.CharField(max_length=255)),
                ('slider3_p1', models.TextField()),
                ('slider3_p2', models.TextField()),
                ('slider4', models.CharField(max_length=255)),
                ('slider4_p1', models.TextField()),
                ('slider4_p2', models.TextField()),
                ('calltoaction', models.CharField(max_length=255)),
                ('calltoaction_p', models.TextField()),
            ],
        ),
    ]
