# Generated by Django 5.0.4 on 2024-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_staticcontentabout'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontentcontact',
            name='base_content',
            field=models.TextField(default=''),
        ),
    ]
