# Generated by Django 5.0.4 on 2024-08-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_staticcontentcontact_base_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticcontentabout',
            name='base_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='call',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontentabout',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='base_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='call',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcontenthome',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
