# Generated by Django 5.0.4 on 2024-08-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_staticcontentblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_content', models.TextField(default='')),
                ('location', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('call', models.CharField(default='', max_length=255)),
                ('twitter_url', models.URLField(default='', max_length=255)),
                ('facebook_url', models.URLField(default='', max_length=255)),
                ('instagram_url', models.URLField(default='', max_length=255)),
                ('linkedin_url', models.URLField(default='', max_length=255)),
            ],
        ),
    ]
