# Generated by Django 5.0.4 on 2024-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_rename_staticcontentcategory_footer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calltoaction', models.CharField(max_length=255)),
                ('calltoaction_p', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='calltoaction',
        ),
        migrations.RemoveField(
            model_name='staticcontentabout',
            name='calltoaction_p',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='calltoaction',
        ),
        migrations.RemoveField(
            model_name='staticcontenthome',
            name='calltoaction_p',
        ),
    ]
