# Generated by Django 5.0.4 on 2024-08-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_calltoaction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='image',
        ),
    ]
