# Generated by Django 5.0.4 on 2024-08-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_calltoaction_remove_staticcontentabout_calltoaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact_banners/')),
            ],
        ),
    ]
