# Generated by Django 5.0.8 on 2024-08-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('url1', models.URLField()),
                ('min_count', models.IntegerField(default=0)),
                ('max_count', models.IntegerField()),
                ('url2', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel1',
        ),
    ]
