# Generated by Django 5.0.7 on 2024-08-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100)),
                ('url_1', models.URLField()),
                ('count_1', models.PositiveIntegerField(default=0)),
                ('count_2', models.PositiveIntegerField(default=10000, editable=False)),
                ('url_2', models.URLField()),
            ],
        ),
    ]
